cars_list.settings:
  type: config_object
  label: 'Cars List settings'
  mapping:
    endpoint:
      type: string
      label: 'Endpoint'
    cache_duration:
      type: integer
      label: 'Cache Duration'
